export const text = {
	borgverse: [
		{
			title: 'planet categories',
			text: [
				{ p: `The <span>borgverse</span> is our take on a sci-fi themed metaverse built on a multi-planetary system. Our goal is to make every single planet a completely different and unique experience for users within the game. By doing this, players are bound to find something they enjoy and are willing to spend their time on playing. When building out planets we break them into 3 categories which are Community, PVP, and Solo.`},
				{ p: `<span>Community planets :</span> These are multiplayer planets that act as safe zones within the borgverse. PLayers that land on these planets are safe from other users and are not able to die/inflict damage. Our galleries are examples of community planets. ON the gallery planets users are able to walk around and interact with each other through a chatting system. Aside from PTP interaction, users are also able to interact with various npcs throughout the planet to make their experience more enjoyable. We spiced up the community planets by adding a jetpack feature that users will be able to unlock. every robot in the borgverse comes with a built-in back attachment. When the jetpack upgrade is unlocked users are able to activate their jetpack whenever they’d like which opens up their character’s back compartment and allows them to fly around the community planets. Community planets are designed for new users to meet each other and then travel to the more exciting PVP planets to partake in competitions.`},
				{ p: `<span>PVP planets :</span> These are action packed player vs player planets with leveling systems, leaderboards, large lobby capacities, and much more. Our goal with the pvp planets is to create a completely different game with unique mechanics on every planet. We are currently building a tank game, racing game, squid games, and a first person shooter. we have already finished and publicly released the hover borgs planet which is a tank based capture the flag game. The games mentioned above are just the 4 that we are hyper focused on currently but the possibilities for what we create in the future are endless. As you’ve noticed, the games above are all completely different genres. We do this on purpose as our goal is to maintain a highly diverse set of pvp planets that offer a fresh experience from planet to planet. `},
				{ p: `<span>Solo planets :</span> Solo planets are a wide array of single player planets with different purposes/games. Our goal with the single player planets is to create an isolating yet fun environment. We want users to have the ability to take a break from the action packed multiplayer aspect experienced throughout the rest of the borgverse. The first solo planet that we have created is a level based parkour game where the levels get tougher as the player progresses. We are also working on an aim trainer planet where users are able to train different aspects of their aim such as reaction time, headshot accuracy, spray control, etc. These are just 2 of many planets that are to come in the single player section of the borgverse. `},
			]
		},
		{
			title: 'transportation',
			text: [
				{ p: `wHEN IT COMES TO Traveling FROM PLANET TO PLANET, USERS HAVE TWO OPTIONS. tHE FIRST IS THROUGH A PORTAL AND THE SECOND IS BY FLYING IN A <span>SPACESHIP</span>. wHEN USING SPACESHIP TRAVEL USERS WILL UTILIZE OUR ELEVATOR SYSTEMS. aT THE CORE OF EVERY PLANET THERE IS A LARGE ELEVATOR SYSTEM THAT TRANSPORTS PLAYERS UP TO THE MAIN AREA. tHE ELEVATORS WORK DIFFERENTLY DEPENDING ON THE PLANET THEY ARE ON. oN THE COMMUNITY PLANETS THE ELEVATORS TAKE YOU TO THE SURFACE. oN THE pvp GAMING PLANETS THE ELEVATORS TAKE YOU TO THE MENU SCREEN FOR THE GAME YOU ARE PLAYING. oN THE SOLO PLANETS IT IS A MIX BETWEEN MENU SCREEN AND SURFACE DEPENDING ON THE STRUCTURE OF THE PLANET AND ITS MECHANICS. `},
				{ p: `<span>pORTAL tRAVEL :</span> eACH PLANET IN THE BORGVERSE HAS A LARGE PORTAL AT THE CENTER OF IT. tHIS PORTAL ACTS AS A GATEWAY BETWEEN ALL OF THE PLANETS WITHIN THE GALAXY. wHEN A USER ENTERS A PORTAL A 3D MENU APPEARS WHERE THEY ARE ABLE TO SELECT WHICH PLANET THEY WISH TO TRAVEL TO. oNCE A PLANET IS SELECTED THE USER IS SENT TO IT THROUGH A LIGHT BEAM AND COMES OUT ON THE OTHER END OF THE PORTAL. Traveling THROUGH THE PORTAL SYSTEM IS THE EASIEST AND FASTEST WAY TO GET AROUND.`},
				{ p: `<span>sPACESHIP TRAVEL :</span> tHIS IS WHERE THINGS GET INTERESTING. eVERY PLANET IN THE BORGVERSE HAS A LARGE LANDING PAD STICKING OUT FROM THE BOTTOM OF THE PLANET. pLAYERS ARE ABLE TO LAND/PARK ON THIS PAD WHICH ACTS AS A CONVEYOR BELT. tHE BELT TAKES THEM INTO THE CORE OF THE PLANET WHERE THE ELEVATOR SYSTEM DOES THE REST OF THE WORK. aSIDE FROM JUST BEING ABLE TO FLY FROM PLANET TO PLANET THE GALAXY IS A PVP ZONE WHERE users ARE ABLE TO FIGHT EACH OTHER. tHIS MEANS THAT YOUR FRIEND viNNY CAN SHOOT YOU DOWN AND CAUSE YOU TO RESPAWN WHEN FLYING FROM THE GALLERY PLANET TO THE HOVER BORGS PLANET. bY ENABLING COMBAT IN SPACE, USERS WILL HAVE A MUCH MORE ENTERTAINING EXPERIENCE WHEN TRAVELING FROM PLANET TO PLANET. wE HAVE ALSO BUILT A SPACESHIP LEVELING SYSTEM WHERE PLAYERS GAIN POINTS BY KILLING OTHER PLAYERS IN SPACE. tHESE POINTS CAN THEN BE USED TO UPGRADE CERTAIN ASPECTS OF THEIR SPACESHIPS SUCH AS SPEED, SHIELD, TURBO, ETC. wE ARE ALSO WORKING ON IMPLEMENTING A MOTHERSHIP WHERE PLAYERS CAN LAND THEIR SPACESHIPS ON AND JOIN pvp SPACESHIP BASED GAMES. fOR EXAMPLE, A PLAYER WOULD LAND ON THE MOTHERSHIP AND THEN ENTER A PUBLIC LOBBY MENU, ON THIS MENU THE PLAYER IS ABLE TO JOIN/CREATE A NEW LOBBY FOR A CAPTURE THE FLAG GAME. tHIS LOBBY IS OPEN FOR OTHER USERS TO JOIN AND TAKES PLACE IN A DESERTED SECTION OF THE GALAXY. uPON COMPLETION OF THE MATCH, THE USERS ARE SENT BACK TO THE MOTHERSHIP LOBBY MENU AND CAN DECIDE WHETHER THEY WANT TO continue TRAVELLING TO A different PLANET OR STAY ON THE MOTHERSHIP AND PLAY MORE OF THE SPACESHIP BASED GAMES. iN OUR EYES THE MOTHERSHIP IS BASICALLY A PVP PLANET BUT IN A DIFFERENT FORM. `},
			]
		}
	],
	goals: [
		{
			title: 'short term goals',
			text: [
				{ p: `<span>Goal #1 :</span> Build out our first 10 planets which are a mix of community, PVP, and solo. we look at these 10 planets as the fundamentals for the borgverse as they are both diverse and offer players a wide range of new experiences. After completing these 10 planets we will be much more open minded to community feedback in regurds to new planets and pvp game creation. 4 of these planets have already been completed (2 community, 1 pvp, 1 solo).` },
				{ p: `<span>Goal #2 :</span> Build out a well organized in game play to earn economy with the help of advisors and economists. Make sure that the coin is integrated into all facets of the borgverse including travel, pvp game leaderboards, task completion, etc. launch IDO offering. ` },
				{ p: `<span>Goal #3 :</span> Integrate a character body customization interface so that players can interchange the body parts of their 3d robot characters as well as perform upgrades and unlock new parts. Traits from nft transfers to in game character.` },
				{ p: `<span>Goal #4 :</span> Bring in new talent into our expanding development team in order to allow us to progress faster in planet creation and borgverse expansion. The more game devs we have working for us, the faster we can pump out new planets which offer completely new experiences.` },
				{ p: `<span>Goal #5 :</span> Expand Our art team in order to produce in-game assets for the pvp planets at a faster pace. (Custom tanks, spaceships, racing cars, boats, etc). Our goal is for a player to be able to customize every single one of their in game vehicles, especially on the pvp planets. ` },
				{ p: `<span>Goal #6 :</span> Hire an in-game event planner to organize in-game events such as project vs project tournaments, live music events, conferences/meetings, project ama’s,  etc.` },
			]
		},
		{
			title: 'long term goals',
			text: [
				{ p: `<span>Goal #1 :</span> Create a launchpad for other projects looking to dive into the crypto gaming ecosystem. We want to create a similar structure to roblox which allows anyone in the community to build their own game on top of the roblox infrastructure. In the borgverse our goal is to allow other projects and people in the space to build their own games/environments on planets which would then be accessible by anyone through our directory system. Allowing other projects and people to build on top of our existing ecosystem allows for there to be endless experiences for players within the borgverse. For example, the roblox game library has over 40 million games that we are all created by members of the community through the roblox studio tool. Having such a large amount of options for users to choose from creates a much more exciting gaming experience as users are able to do pretty much anything they want. This is a very complex and ambitious goal but is something that would revolutionize the crypto gaming space as we know it` },
				{ p: `<span>Goal #2 :</span> Create a bridge between the solana and ethereum ecosystem to give users the choice to connect and play using either of their wallets. We strongly believe that in order for a game to continually grow it needs to be playable by users from different ecosystems. Not everyone in the crypto space has a phantom wallet, so allowing users to connect with wallets from different ecosystems while maintaining the same overall experience is crucial to user base growth.` },
				{ p: `<span>Goal #3 :</span> Build an in game marketplace planet that allows users to buy/sell/trade with each other. Creating an in game marketplace for users to sell their in game assets on is extremely important as it allows everything to stay within the borgverse ecosystem. we would eliminate the need for third party service providers which is something that would enhance the players experience as everything could be done in one place with a custom system that is tailored towards the user base. ` },
			]
		},
	]
};


